AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to deploy Cognito User Pool with username/password signup and login and triggers

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CourseTrackerUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
      MfaConfiguration: OFF
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      LambdaConfig:
        PreSignUp: !GetAtt PreSignUpFunction.Arn
        PostConfirmation: !GetAtt PostConfirmationFunction.Arn

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: CourseTrackerUserPoolClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_CUSTOM_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO

  PreSignUpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CourseTrackerPreSignUp
      Handler: index.handler
      Runtime: node18.x
      CodeUri: ./lambda/pre_signup/
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaCognitoExecutionRole

  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CourseTrackerPostConfirmation
      Handler: index.handler
      Runtime: node18.x
      CodeUri: ./lambda/post_confirmation/
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  UserPoolId:
    Description: Cognito User Pool Id
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Description: Cognito User Pool Client Id
    Value: !Ref CognitoUserPoolClient
